### ISSUE TITLE
Indexing failure

### ISSUE THREAD

**Issue by schmeter** [yss/grunt-tree#10]
Job won't work on trees like this:

img/
├── 0
│   ├── 1.1.jpg
│   ├── 1.2.jpg
│   ├── 1.3.jpg
│   ├── 1.4.jpg
│   ├── 1.5.jpg
│   ├── 1.6.jpg
│   ├── 1.7.jpg
│   ├── 1.8.jpg
│   └── 1.jpg
├── 1
│   ├── 1.jpg
│   ├── 2.jpg
│   ├── 3.1.jpg
│   ├── 3.2.png
│   ├── 3.3.png
│   ├── 3.jpg
│   └── 4.jpg
├── 2
│   ├── 1.jpg
│   ├── 2.jpg
│   └── 3.jpg
├── 3
│   ├── 1.jpg
│   ├── 2.jpg
│   └── 3.jpg
├── 4
│   ├── 1.1.jpg
│   ├── 1.2.png
│   ├── 1.3.png
│   ├── 1.jpg
│   ├── 2.1.jpg
│   ├── 2.2.png
│   ├── 2.jpg
│   ├── 3.1.jpg
│   ├── 3.2.png
│   ├── 3.3.png
│   ├── 3.jpg
│   ├── 4.1.jpg
│   ├── 4.2.png
│   ├── 4.jpg
│   ├── 5.1.jpg
│   ├── 5.2.png
│   ├── 5.3.png
│   ├── 5.jpg
│   ├── 6.1.jpg
│   ├── 6.2.png
│   ├── 6.3.png
│   ├── 6.4.png
│   ├── 6.jpg
│   ├── 7.jpg
│   └── 8.jpg
├── 5
│   ├── 1.jpg
│   ├── 2.jpg
│   └── 3.jpg
├── 6
│   ├── 1.jpg
│   └── 2.jpg
└── 7
    ├── 1.jpg
    └── 2.jpg

result is wrong:

{
    "img": {
        "0": {
            "1.2": "img/0/1.2.jpg",
            "1.3": "img/0/1.3.jpg",
            "1.4": "img/0/1.4.jpg",
            "1.5": "img/0/1.5.jpg",
            "1.6": "img/0/1.6.jpg",
            "1.7": "img/0/1.7.jpg",
            "1.8": "img/0/1.8.jpg"
        },
        "4": {
            "4": "img/4/4.jpg",
            "5": "img/4/5.jpg",
            "6": "img/4/6.jpg",
            "7": "img/4/7.jpg",
            "8": "img/4/8.jpg",
            "1.1": "img/4/1.1.jpg",
            "3.1": "img/4/3.1.jpg",
            "2.1": "img/4/2.1.jpg",
            "4.1": "img/4/4.1.jpg",
            "5.1": "img/4/5.1.jpg",
            "6.1": "img/4/6.1.jpg"
        },
        "5": {
            "3": "img/5/3.jpg"
        },
        "7": {
            "1": "img/7/1.jpg",
            "2": "img/7/2.jpg"
        }
    }
}

**Comment by honkskillet** [comment]
@yss @schmeter  I noticed this too.  There is a bugs somewhere in the code such that if the prefix of a file is the same as another file, only the last file will end up in the outputted JSON.

For example

> img/
├── 0
│   ├── 1.jpg
│   ├── 1.gif

will only output
{"img":{"0": {"1":"img/0/1/gif"}}}

this is also true if the files are in different folders.  For example
> img/
├── 0
│   ├── 1.jpg
├── 1
│   ├── 1.jpg
will only output
{"img":{"1": {"1":"img/1/1/jpg"}}}

This is a critical bug.  There must be a fundamental error in the recursive algorithm being used.

**Comment by honkskillet** [comment]
The source of the problem is this line

    this._tree[extFileName] = Path.join(options.cwd, subdir, this.getFileName(abspath, filename));

extFileName is the prefix of a file.  So  /img/gifs/first.gif and /src/scripts/first.js have the same extFileName.  If there is already an entry in this._tree with the key "first", a 2nd file will overwrite the first.

**Comment by honkskillet** [comment]
parseTreeWithNoFormat: function(){....}
will also overwrite keys.  For example first.js and first.css will overwrite each other and you will only end up with on entry.

**Comment by yss** [comment]
Yeah, this problem is very serious!
And I will resolve it by new way。
The follow is what i want to do:
```
img/
├── 0
│ ├── 1.jpg
├── 1
│ ├── 1.jpg
will only output
{"img/0/1.jpg": "xxxx-1.jpg", "img/1/1.jpg": "xxxx-1.jpg"}
or
{"img":{"0":{"1.jpg": "1.jpg"}, "1": {"1.jpg": "1.jpg"}}
```

**Comment by yss** [comment]
version 1.0.1 published! 
if you can, please use v1.0.1
