### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by AdrianDroid** [yss/grunt-tree#9]
" Running "tree:json" (tree) task
Warning: path must be a string Use --force to continue.

Aborted due to warnings. " 

no error before. 

the version  number haven't update but the code changed?

**Comment by michael-zucchetta** [comment]
I have the same issue on the version 0.4.8, my config is:
```javascript 
        tree: {
                    options: {
                             format: true
                     },
                    js: {
                            options: {
                                    type: ['js']
                            },
                            files: [
                                    {
                                            src: ['dist/'],
                                            dest: filesPath
                                    }
                            ]
                    }
            }
```
I think it's breaking at the line 146, on the function grunt.file.recurse
I tried to print the filepath at line 145 of the tree.js and I get:
```javascript
 { src: [Getter],
 dest: 'dist/files.json',
  orig: { src: [ 'dist/' ], dest: 'dist/files.json' } }
```

**Comment by yss** [comment]
I am so sorry see this. It is a fatal error for cannot forgive me.
I missing github long time.
Anyway, the new version 0.4.9 published.
Thank you all for use this plugin.
